version: 1
runtime: python311
env: flex 
threadsafe: true
entrypoint: "uvicorn api:app --host 0.0.0.0 --port 8080"

handlers:
- url: /health
  script: auto

- url: /predict
  script: auto
  secure: always
  login: optional
  http_headers:
    Access-Control-Allow-Origin: "*"
  redirect_http_response_code: 301
  http_method: post
